### PR TITLE
Explicitly call FormSpec to clean and split

### PR DESCRIPTION
**Pull request by chrzyki**
This addresses #7 and explicitly calls `FormSpec()` to clean forms of the issues mentioned in #7. I'd much appreciate it if you could quickly check whether the cleaned (and split) forms are still 'sane' and make sense.

### CODE REVIEW

**Review by LinguList — COMMENTED** [review]
Where do these duplicated entries in the forms come from? They seem to be identical. I think, the formspec should rather be first-form-only, or is there anything else going on? The problem is: the tokens are now duplicated, but the second form should also be segmentized. So it is better to ignore this in the formspec and not split, rather "firstformonly".

**Comment by chrzyki** [comment]
They split now at the full width comma, thus a value like `ʊ²⁴，ʊ²¹²` leads to two forms:

```
Hefei-806_ifirstpersonsingular-1,,Hefei,806_ifirstpersonsingular,ʊ²⁴，ʊ²¹²,ʊ²⁴,ʊ ²⁴,,Cihui,,,,,我
Hefei-806_ifirstpersonsingular-2,,Hefei,806_ifirstpersonsingular,ʊ²⁴，ʊ²¹²,ʊ²¹²,ʊ ²⁴,,Cihui,,,,,我
```

But you're right, the segmentation is done only for the first form. I can remove the comma splitting and only do the cleaning, reverting this back to the old behaviour.

**Comment by LinguList** [comment]
The segmentation is based on the wordlist, it is already done, so no splitting should be carried out here, and the second form ignored.

**Comment by chrzyki** [comment]
Updated the PR, this now only does the form cleaning by explicitly calling `FormSpec()`.

**Review by LinguList — APPROVED** [review]

**Pull request merged**
